/**
 * YAML generation functions for CronoStar Editor
 */

import { normalizePrefix, getAliasWithPrefix } from '../../utils/prefix_utils.js';

/**
 * Builds the automation YAML with new HA syntax (2025+)
 */
export function buildAutomationYaml(config, style = 'list') {
  const applyEntity = config.target_entity;
  const pauseEntity = config.pause_entity;
  const profilesSelect = config.profiles_select_entity || '';
  const interval = config.interval_minutes || 60;

  const rawPrefix = normalizePrefix(config.global_prefix || 'cronostar_');
  const idBase = rawPrefix.replace(/_+$/, '');
  const id = `${idBase}_apply`;

  const alias = getAliasWithPrefix(rawPrefix, 'en');

  // Determine target entities
  const domain = (applyEntity || '').split('.')[0];
  const isClimate = domain === 'climate';
  const isNumber = domain === 'number';
  const isSwitch = domain === 'switch';

  const lines = [];

  if (style === 'inline') {
    lines.push('automation:');
  }

  const indent = style === 'inline' ? '  ' : '';

  // Header
  lines.push(`${indent}- id: ${id}`);
  lines.push(`${indent}  alias: "${alias}"`);
  lines.push(`${indent}  description: "Generated by CronoStar Editor"`);
  lines.push(`${indent}  mode: restart`);

  // Triggers
  lines.push(`${indent}  triggers:`);

  // Time pattern trigger
  lines.push(`${indent}    - trigger: time_pattern`);
  if (interval === 60) {
    lines.push(`${indent}      minutes: "0"`);
  } else {
    lines.push(`${indent}      minutes: "/${interval}"`);
  }

  // Event trigger (when profiles are loaded)
  lines.push(`${indent}    - trigger: event`);
  lines.push(`${indent}      event_type: cronostar_profiles_loaded`);

  // Conditions
  if (pauseEntity) {
    lines.push(`${indent}  conditions:`);
    lines.push(`${indent}    - condition: state`);
    lines.push(`${indent}      entity_id: ${pauseEntity}`);
    lines.push(`${indent}      state: "off"`);
  } else {
    lines.push(`${indent}  conditions: []`);
  }

  // Actions
  lines.push(`${indent}  actions:`);

  // Variable definitions
  lines.push(`${indent}    - variables:`);
  lines.push(`${indent}        current_hour: "{{ now().hour }}"`);
  lines.push(`${indent}        hour_str: "{{ '%02d' | format(current_hour) }}"`);
  lines.push(`${indent}        target_input: "input_number.${rawPrefix}{{ hour_str }}"`);

  // Determine default value based on domain
  let defaultVal = '20';
  if (isSwitch) defaultVal = '0';
  if (isNumber) defaultVal = '0';

  lines.push(`${indent}        target_value: "{{ states(target_input) | float(${defaultVal}) }}"`);

  // Log action
  lines.push(`${indent}    - action: system_log.write`);
  lines.push(`${indent}      data:`);
  lines.push(`${indent}        message: "[CronoStar] Applying {{ target_value }} to ${applyEntity}"`);
  lines.push(`${indent}        level: info`);

  // Apply action based on domain
  if (isClimate) {
    lines.push(`${indent}    - action: climate.set_temperature`);
    lines.push(`${indent}      target:`);
    lines.push(`${indent}        entity_id: ${applyEntity}`);
    lines.push(`${indent}      data:`);
    lines.push(`${indent}        temperature: "{{ target_value }}"`);
  } else if (isNumber) {
    lines.push(`${indent}    - action: number.set_value`);
    lines.push(`${indent}      target:`);
    lines.push(`${indent}        entity_id: ${applyEntity}`);
    lines.push(`${indent}      data:`);
    lines.push(`${indent}        value: "{{ target_value }}"`);
  } else if (isSwitch) {
    lines.push(`${indent}    - if:`);
    lines.push(`${indent}        - condition: template`);
    lines.push(`${indent}          value_template: "{{ target_value | int > 0 }}"`);
    lines.push(`${indent}      then:`);
    lines.push(`${indent}        - action: switch.turn_on`);
    lines.push(`${indent}          target:`);
    lines.push(`${indent}            entity_id: ${applyEntity}`);
    lines.push(`${indent}      else:`);
    lines.push(`${indent}        - action: switch.turn_off`);
    lines.push(`${indent}          target:`);
    lines.push(`${indent}            entity_id: ${applyEntity}`);
  } else {
    // Generic/Unknown entity fallback
    lines.push(`${indent}    # TODO: Add specific action for ${applyEntity}`);
    lines.push(`${indent}    # - action: domain.service`);
    lines.push(`${indent}    #   target:`);
    lines.push(`${indent}    #     entity_id: ${applyEntity}`);
    lines.push(`${indent}    #   data:`);
    lines.push(`${indent}    #     value: "{{ target_value }}"`);
  }

  return lines.join('\n');
}

/**
 * Builds the helper entities YAML (Package)
 */
export function buildInputNumbersYaml(config, isInline = false) {
  const presetName = getPresetDisplayName(config.preset || 'thermostat');
  const rawPrefix = normalizePrefix(config.global_prefix || 'cronostar_');

  const min = config.min_value ?? 0;
  const max = config.max_value ?? 30;
  const step = config.step_value ?? 0.5;
  const unit = config.unit_of_measurement || '';
  const mode = 'box';

  const pauseEntity = config.pause_entity;
  const profilesEntity = config.profiles_select_entity;
  const applyEntity = config.target_entity;

  const lines = [];
  const isList = false; // Package format usually uses dictionary keys

  // 1. INPUT NUMBERS
  if (isInline) lines.push('input_number:');

  // Current value helper
  const indent = isInline ? '  ' : '';
  lines.push(`${indent}${rawPrefix}current:`);
  lines.push(`${indent}  name: "CronoStar ${presetName} Current"`);
  lines.push(`${indent}  min: ${min}`);
  lines.push(`${indent}  max: ${max}`);
  lines.push(`${indent}  step: ${step}`);
  if (unit) lines.push(`${indent}  unit_of_measurement: "${unit}"`);
  lines.push(`${indent}  mode: ${mode}`);
  lines.push(`${indent}  icon: mdi:chart-timeline`);

  // 2. INPUT BOOLEAN (Pause)
  if (pauseEntity) {
    lines.push('');
    if (isInline) lines.push('input_boolean:');
    // Always enforce correct prefix for the helper key
    const pauseKey = `${rawPrefix}paused`;

    lines.push(`${indent}${pauseKey}:`);
    lines.push(`${indent}  name: "CronoStar ${presetName} Paused"`);
    lines.push(`${indent}  icon: mdi:pause-circle`);
  }

  // 3. INPUT SELECT (Profiles)
  if (profilesEntity) {
    lines.push('');
    if (isInline) lines.push('input_select:');
    // Always enforce correct prefix for the selector key
    const profileKey = `${rawPrefix}profiles`;

    lines.push(`${indent}${profileKey}:`);
    lines.push(`${indent}  name: "CronoStar ${presetName} Profiles"`);
    lines.push(`${indent}  options:`);
    lines.push(`${indent}    - "Default"`);
    lines.push(`${indent}  initial: "Default"`);
    lines.push(`${indent}  icon: mdi:format-list-bulleted`);
  }

  // 4. INPUT TEXT (Target entity) - optional but useful for discovery/debug
  if (applyEntity) {
    lines.push('');
    if (isInline) lines.push('input_text:');
    const key = `${rawPrefix}target_entity`;
    lines.push(`${indent}${key}:`);
    lines.push(`${indent}  name: "CronoStar ${presetName} Target Entity"`);
    lines.push(`${indent}  initial: "${applyEntity}"`);
    lines.push(`${indent}  icon: mdi:target`);
  }

  return lines.join('\n');
}

function getPresetDisplayName(preset) {
  const map = {
    thermostat: 'Thermostat',
    ev_charging: 'EV Charging',
    generic_kwh: 'Generic kWh',
    generic_temperature: 'Generic Temperature',
    generic_switch: 'Generic Switch'
  };
  return map[preset] || preset;
}
