/**
 * YAML generation functions for CronoStar Editor
 */

import { normalizePrefix, getAliasWithPrefix } from '../../utils/prefix_utils.js';

/**
 * Builds the automation YAML with new HA syntax (2025+)
 */
export function buildAutomationYaml(config, style = 'list') {
  const applyEntity = config.target_entity;
  const pauseEntity = config.pause_entity;
  const interval = config.interval_minutes || 60;
  const preset = config.preset || 'thermostat';

  const rawPrefix = normalizePrefix(config.global_prefix || 'cronostar_');
  const idBase = rawPrefix.replace(/_+$/, '');
  const id = `${idBase}_apply`;

  const alias = getAliasWithPrefix(rawPrefix, 'en');

  const lines = [];

  if (style === 'inline') {
    lines.push('automation:');
  }

  const indent = style === 'inline' ? '  ' : '';

  // Header
  lines.push(`${indent}- id: ${id}`);
  lines.push(`${indent}  alias: "${alias}"`);
  lines.push(`${indent}  description: "Generated by CronoStar Editor"`);
  lines.push(`${indent}  mode: restart`);

  // Triggers
  lines.push(`${indent}  triggers:`);

  // Time pattern trigger
  lines.push(`${indent}    - trigger: time_pattern`);
  if (interval === 60) {
    lines.push(`${indent}      minutes: "0"`);
  } else {
    lines.push(`${indent}      minutes: "/${interval}"`);
  }

  // Event trigger (when profiles are loaded)
  lines.push(`${indent}    - trigger: event`);
  lines.push(`${indent}      event_type: cronostar_profiles_loaded`);

  // Conditions
  if (pauseEntity) {
    lines.push(`${indent}  conditions:`);
    lines.push(`${indent}    - condition: state`);
    lines.push(`${indent}      entity_id: ${pauseEntity}`);
    lines.push(`${indent}      state: "off"`);
  } else {
    lines.push(`${indent}  conditions: []`);
  }

  // Actions
  lines.push(`${indent}  actions:`);
  lines.push(`${indent}    - action: cronostar.apply_now`);
  lines.push(`${indent}      data:`);
  lines.push(`${indent}        target_entity: "${applyEntity}"`);
  lines.push(`${indent}        preset_type: "${preset}"`);
  lines.push(`${indent}        global_prefix: "${rawPrefix}"`);

  return lines.join('\n');
}

/**
 * Builds the helper entities YAML (Package)
 */
export function buildInputNumbersYaml(config, isInline = false) {
  const presetName = getPresetDisplayName(config.preset || 'thermostat');
  const rawPrefix = normalizePrefix(config.global_prefix || 'cronostar_');

  const min = config.min_value ?? 0;
  const max = config.max_value ?? 30;
  const step = config.step_value ?? 0.5;
  const unit = config.unit_of_measurement || '';
  const mode = 'box';

  const pauseEntity = config.pause_entity;
  const profilesEntity = config.profiles_select_entity;
  const applyEntity = config.target_entity;

  const lines = [];

  // 1. INPUT NUMBERS
  if (isInline) lines.push('input_number:');

  // Current value helper
  const indent = isInline ? '  ' : '';
  lines.push(`${indent}${rawPrefix}current:`);
  lines.push(`${indent}  name: "CronoStar ${presetName} Current"`);
  lines.push(`${indent}  min: ${min}`);
  lines.push(`${indent}  max: ${max}`);
  lines.push(`${indent}  step: ${step}`);
  if (unit) lines.push(`${indent}  unit_of_measurement: "${unit}"`);
  lines.push(`${indent}  mode: ${mode}`);
  lines.push(`${indent}  icon: mdi:chart-timeline`);

  // 2. INPUT BOOLEAN (Pause)
  if (pauseEntity) {
    lines.push('');
    if (isInline) lines.push('input_boolean:');
    // Always enforce correct prefix for the helper key
    const pauseKey = `${rawPrefix}paused`;

    lines.push(`${indent}${pauseKey}:`);
    lines.push(`${indent}  name: "CronoStar ${presetName} Paused"`);
    lines.push(`${indent}  icon: mdi:pause-circle`);
  }

  // 3. INPUT SELECT (Profiles)
  if (profilesEntity) {
    lines.push('');
    if (isInline) lines.push('input_select:');
    // Always enforce correct prefix for the selector key
    const profileKey = `${rawPrefix}profiles`;

    lines.push(`${indent}${profileKey}:`);
    lines.push(`${indent}  name: "CronoStar ${presetName} Profiles"`);
    lines.push(`${indent}  options:`);
    lines.push(`${indent}    - "Default"`);
    lines.push(`${indent}  initial: "Default"`);
    lines.push(`${indent}  icon: mdi:format-list-bulleted`);
  }

  // 4. INPUT TEXT (Target entity) - optional but useful for discovery/debug
  if (applyEntity) {
    lines.push('');
    if (isInline) lines.push('input_text:');
    const key = `${rawPrefix}target_entity`;
    lines.push(`${indent}${key}:`);
    lines.push(`${indent}  name: "CronoStar ${presetName} Target Entity"`);
    lines.push(`${indent}  initial: "${applyEntity}"`);
    lines.push(`${indent}  icon: mdi:target`);
  }

  return lines.join('\n');
}

function getPresetDisplayName(preset) {
  const map = {
    thermostat: 'Thermostat',
    ev_charging: 'EV Charging',
    generic_kwh: 'Generic kWh',
    generic_temperature: 'Generic Temperature',
    generic_switch: 'Generic Switch'
  };
  return map[preset] || preset;
}
