blueprint:
  name: CronoStar - Apply profile hourly
  description: Apply the CronoStar profile every hour to a target entity.
  domain: automation
  input:
    target_entity:
      name: Target Entity
      description: The entity to apply the profile to (climate, number, switch).
      selector:
        entity: {}
    preset_type:
      name: Preset Type
      description: The type of preset (thermostat, ev_charging, generic_kwh, generic_temperature, generic_switch).
      default: thermostat
      selector:
        select:
          options:
            - thermostat
            - ev_charging
            - generic_kwh
            - generic_temperature
            - generic_switch
    pause_entity:
      name: Pause Entity
      description: Optional input_boolean to pause the automation.
      default: ""
      selector:
        entity:
          domain: input_boolean

mode: restart

trigger:
  - trigger: time_pattern
    minutes: "0"

action:
  - variables:
      pause_ent: !input pause_entity
  - condition: template
    value_template: "{{ pause_ent == '' or states(pause_ent) != 'on' }}"
  - action: cronostar.apply_now
    data:
      target_entity: !input target_entity
      preset_type: !input preset_type