name: Validate with HACS
on:ush:
  push:request:
  pull_request:
  schedule: "0 0 * * *"
    - cron: "0 0 * * *"
jobs:idate:
  validate:: ubuntu-latest
    runs-on: ubuntu-latest
    steps:es: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:egory: integration
          category: integration
